---

- name: Install Mediawiki
  hosts: cl_app
  vars_files:
    - vars/secrets.yml
    - vars/main.yml
  vars:
    db_server: "{{ hostvars[groups['cl_db'][0]]['vagrant_ip_address'] }}"
    db_maintain: true
  become: yes
  roles:
    - mediawiki

