---

- name: Install Mediawiki
  hosts: cl_app
  vars_files:
    - vars/secrets.yml
    - vars/main.yml
  vars:
    mediawiki_db_server: "{{ hostvars[groups['cl_db'][0]]['vagrant_ip_address'] }}"
    mediawiki_db: "{{ mysql_databases[0]['name']  }}" 
    mediawiki_db_user: "{{ mysql_users[0]['name'] }}"
    mediawiki_db_pass: "{{ mysql_wikimed_password }}"
    setup_db: false
  become: yes
  roles:
    - mediawiki

