dependency_pkgs:
  - apache2
  - php
  - php-common
  - php-mbstring
  - php-xmlrpc
  - php-soap
  - php-gd
  - php-xml
  - php-intl 
  - php-mysql 
  - php-cli 
  - php-ldap 
  - php-zip 
  - php-curl
  - libapache2-mod-php
  - php-json
