dependency_pkgs:
  - httpd
  - php
  - php-common
  - php-mbstring
  - php-xmlrpc
  - php-soap
  - php-gd
  - php-xml
  - php-intl 
  - php-mysqlnd 
  - php-cli 
  - php-ldap 
  - php-zip 
  - php-curl
  - php-json
